# Generated by Django 4.2.2 on 2023-06-24 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_menu"),
    ]

    operations = [
        migrations.AlterModelOptions(name="restaurant", options={},),
        migrations.AlterModelOptions(name="user", options={},),
        migrations.AddField(
            model_name="menu",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="menu",
            name="last_modified",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterModelTable(name="menu", table="menu",),
        migrations.AlterModelTable(name="restaurant", table="restaurant",),
        migrations.AlterModelTable(name="user", table="user",),
    ]
