# Generated by Django 4.2.2 on 2023-06-24 18:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "get_latest_by": "created_at",
                "ordering": ("-created_at", "-last_modified"),
            },
        ),
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="order",
            name="last_modified",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "last_modified",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("en_route", "En route"),
                            ("completed", "Completed"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "delivery_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.user"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.order"
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-last_modified"),
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
    ]
