# Generated by Django 4.2.2 on 2023-06-24 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_user_managers_user_date_joined_user_groups_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(name="user", managers=[],),
    ]
