# Generated by Django 4.2.2 on 2023-06-24 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("api", "0009_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("permissions", models.ManyToManyField(to="auth.permission")),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.role"
            ),
        ),
    ]
