# Generated by Django 4.2.2 on 2023-06-24 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_user_password_role_alter_user_role"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="role",),
    ]
