# Generated by Django 4.2.2 on 2023-06-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=0,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterModelTable(name="role", table="role",),
    ]
